// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBumwDi6n0s9pTzCLOlynYpfA2OfQq1KhY',
    appId: '1:542494010671:web:c8199feb9eaf7c25e645da',
    messagingSenderId: '542494010671',
    projectId: 'final-pfe-project',
    authDomain: 'final-pfe-project.firebaseapp.com',
    storageBucket: 'final-pfe-project.appspot.com',
    measurementId: 'G-MC4176NCDB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuUe4qAerlbV9Nbhdk2LaSxmj0SDUveXo',
    appId: '1:542494010671:android:d0cdcc52b1b5a47fe645da',
    messagingSenderId: '542494010671',
    projectId: 'final-pfe-project',
    storageBucket: 'final-pfe-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhDptR-KK6QmuqXUuadpchOQpmUfXJOGE',
    appId: '1:542494010671:ios:dcb8d9f49c901bc8e645da',
    messagingSenderId: '542494010671',
    projectId: 'final-pfe-project',
    storageBucket: 'final-pfe-project.appspot.com',
    iosBundleId: 'com.example.applicationGestionDesReclamationsPfe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhDptR-KK6QmuqXUuadpchOQpmUfXJOGE',
    appId: '1:542494010671:ios:dcb8d9f49c901bc8e645da',
    messagingSenderId: '542494010671',
    projectId: 'final-pfe-project',
    storageBucket: 'final-pfe-project.appspot.com',
    iosBundleId: 'com.example.applicationGestionDesReclamationsPfe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBumwDi6n0s9pTzCLOlynYpfA2OfQq1KhY',
    appId: '1:542494010671:web:fd985f0ded7e8003e645da',
    messagingSenderId: '542494010671',
    projectId: 'final-pfe-project',
    authDomain: 'final-pfe-project.firebaseapp.com',
    storageBucket: 'final-pfe-project.appspot.com',
    measurementId: 'G-M96C9898DC',
  );

}